<?php

/**
 * @file
 * Implementation of Link Fields for IBM Use Case.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\node\NodeInterface;
use Drupal\Component\Utility\UrlHelper;
use Acquia\ContentHubClient\Entity as ContentHubEntity;

const IBM_CONTENTHUB_LINKFIELD_LINK_NODE_PATH     = 'ibm_contenthub_link_node_path';
const IBM_CONTENTHUB_LINKFIELD_LINK_NODE_FRAGMENT = 'ibm_contenthub_link_node_fragment';

/**
 * Allows modules to modify the CDF before it is sent to the Content Hub.
 *
 * Common Data Format (CDF): https://docs.acquia.com/content-hub/cdf.
 *
 * This is very useful to modify the CDF (usually its attributes) before
 * it is sent to the Content Hub during the normalization process.
 * Note that the changes will be reflected in the entity published in Content
 * Hub, but the local Drupal entity will not be affected.
 *
 * @param \Acquia\ContentHubClient\Entity $contenthub_entity
 *   The Content Hub CDF.
 */
function ibm_contenthub_linkfield_acquia_contenthub_cdf_from_drupal_alter(ContentHubEntity $contenthub_entity) {
  // Adding changes to the 'redirect' entity types.
  if ($contenthub_entity->getType() == 'node') {
    $entity_repository = \Drupal::service("entity.repository");
    if ($entity = $entity_repository->loadEntityByUuid("node", $contenthub_entity->getUuid())) {
      // Obtain all the link fields in the node.
      $link_fields = ibm_contenthub_linkfield_extract_destination_entities($entity);

      // For each link field, change the NID to UUID in each URI.
      foreach ($link_fields as $name => $data) {
        $values = $contenthub_entity->getAttribute($name)->getValues();
        foreach ($values as $language => $value) {
          foreach ($value as $key => $item) {
            $val = json_decode($item, TRUE);
            $uri = $val['uri'];
            foreach ($link_fields[$name]['node_path']['nid'] as $i => $nid) {
              $uuid = $link_fields[$name]['node_path']['uuid'][$i];
              $uri = str_replace($nid, $uuid, $uri);
            }
            foreach ($link_fields[$name]['node_fragment']['nid'] as $i => $nid) {
              $uuid = $link_fields[$name]['node_fragment']['uuid'][$i];
              $uri = str_replace($nid, $uuid, $uri);
            }
            $val['uri'] = $uri;
            $values[$language][$key] = json_encode($val);
          }
        }
        $contenthub_entity->getAttribute($name)->setValues($values);
      }
    }
  }
}

/**
 * Allows modules to modify the CDF before converting to Drupal Entity.
 *
 * Common Data Format (CDF): https://docs.acquia.com/content-hub/cdf.
 *
 * This is useful to modify the CDF that has been fetched from the Content
 * Hub before it has been converted to Drupal Entity during the denormalization
 * process.
 * Note that we these changes affect the local entity imported from Content Hub
 * but do not affect the entity in Content Hub itself.
 *
 * @param \Acquia\ContentHubClient\Entity $contenthub_entity
 *   The Content Hub CDF.
 */
function sdsdibm_contenthub_linkfield_acquia_contenthub_cdf_from_hub_alter(ContentHubEntity $contenthub_entity) {
  if ($contenthub_entity->getType() == 'node') {

    /** @var \Drupal\Core\Entity\EntityRepositoryInterface $entity_repository */
    $entity_repository = \Drupal::service("entity.repository");

    // Always check that the changes have already been applied, because the
    // normalizer could be called more than once during the export process.
    if ($contenthub_entity->getAttribute('language') === FALSE) {
      $language_field = $contenthub_entity->getAttribute('langcode');
      $contenthub_entity['attributes']['language'] = $language_field;
    }

    // Loading the two fields and checking which ones of those have data.
    $attribute_node_path = $contenthub_entity->getAttribute(IBM_CONTENTHUB_LINKFIELD_LINK_NODE_PATH);
    $attribute_node_fragment = $contenthub_entity->getAttribute(IBM_CONTENTHUB_LINKFIELD_LINK_NODE_FRAGMENT);





    // Setting back the 'redirect_redirect' field.
    if ($redirect_attribute) {
      $redirect_redirect = new Attribute(Attribute::TYPE_ARRAY_STRING);
      $values = $redirect_attribute['value'];
      foreach ($values as $language => $value) {
        $uuid = reset($value);

        // Try to load the entity.
        if ($entity = $entity_repository->loadEntityByUuid($entity_type, $uuid)) {

          $redirect_redirect = (array) $redirect_redirect;
          $url = $entity->toUrl();
          // Setting the redirect value array.

          $redirect_value = [
            'uri' => 'internal:' . base_path() . $url->getInternalPath(),
            'title' => NULL,
            'options' => [],
          ];
          $json_value = json_encode($redirect_value, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT);
          $redirect_redirect['value'] = [
            $language => [
              $json_value,
            ],
          ];
        }
        else {
          // We did not find the entity then do not try to save this redirect.
        }
      }
      $contenthub_entity['attributes']['redirect_redirect'] = $redirect_redirect;
      if ($entity_type === 'node') {
        $contenthub_entity->removeAttribute(IBM_CONTENTHUB_REDIRECT_ATTRIBUTE_NODE);
      }
      elseif ($entity_type == 'taxonomy_term') {
        $contenthub_entity->removeAttribute(IBM_CONTENTHUB_REDIRECT_ATTRIBUTE_TERM);
      }
    }
  }
}

/**
 * Implements hook_entity_base_field_info().
 */
function ibm_contenthub_linkfield_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() === 'node') {
    $fields = [];
    $fields[IBM_CONTENTHUB_LINKFIELD_LINK_NODE_PATH] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Node dependencies'))
      ->setDescription(t('Computed field to add entity dependencies to node entities in link field paths.'))
      ->setComputed(TRUE)
      ->setCustomStorage(TRUE)
      ->setClass('\\Drupal\\ibm_contenthub_linkfield\\Field\\EntityReferenceLinkField');
    $fields[IBM_CONTENTHUB_LINKFIELD_LINK_NODE_FRAGMENT] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Node dependencies'))
      ->setDescription(t('Computed field to add entity dependencies to node entities in link field fragments.'))
      ->setComputed(TRUE)
      ->setCustomStorage(TRUE)
      ->setClass('\\Drupal\\ibm_contenthub_linkfield\\Field\\EntityReferenceLinkField');
    return $fields;
  }
}

/**
 * Extracts the two referenced entities from a LinkField.
 *
 * @param \Drupal\node\NodeInterface $entity
 *   A Node Entity.
 *
 * @return array
 *   The entities.
 */
function ibm_contenthub_linkfield_extract_destination_entities(NodeInterface $entity) {
  $output = [];
  $link_fields = ibm_contenthub_linkfield_locate_linkfields($entity);
  foreach ($link_fields as $field => $item) {
    $values = $entity->get($field)->getValue();
    foreach ($values as $value) {
      $uri = !empty($value['uri']) ? $value['uri'] : FALSE;
      if ($uri) {
        $parts = UrlHelper::parse($uri);
        $path = pathinfo($parts['path']);
        if ($path['dirname'] == 'internal:/node') {
          $nid_path = $path['basename'];
          $nid_fragment = $parts['fragment'];
          if (is_numeric($nid_path)) {
            if ($uuid = ibm_contenthub_linkfield_get_node_uuid_from_nid($nid_path)) {
              $output[$field]['node_path']['nid'][] = $nid_path;
              $output[$field]['node_path']['uuid'][] = $uuid;
            }
          }
          if (is_numeric($nid_fragment)) {
            if ($uuid = ibm_contenthub_linkfield_get_node_uuid_from_nid($nid_fragment)) {
              $output[$field]['node_fragment']['nid'][] = $nid_fragment;
              $output[$field]['node_fragment']['uuid'][] = ibm_contenthub_linkfield_get_node_uuid_from_nid($nid_fragment);
            }
          }
        }
      }
    }
  }
  return $output;
}

/**
 * Helper function to obtain the UUID from NID.
 *
 * @param int $nid
 *   The node nid.
 *
 * @return string
 *   The node UUID.
 */
function ibm_contenthub_linkfield_get_node_uuid_from_nid($nid) {
  $query = \Drupal::database()->select('node')
    ->fields('node', ['uuid']);
  $query->condition("node.nid", $nid);
  return $query->execute()->fetchField();
}

/**
 * Locates all Link fields in the entity.
 *
 * @param \Drupal\node\NodeInterface $entity
 *   A Node Entity.
 *
 * @return \Drupal\Core\Field\FieldItemList[]
 *   An array of link fields.
 */
function ibm_contenthub_linkfield_locate_linkfields(NodeInterface $entity) {
  $link_fields = [];
  $fields = $entity->getFields();
  foreach ($fields as $name => $field) {
    if ($field->getFieldDefinition()->getType() == 'link') {
      $link_fields[$name] = $field;
    }
  }
  return $link_fields;
}
