<?php

/**
 * @file
 */

use Acquia\ContentHubClient\Entity as ContentHubEntity;
use Acquia\ContentHubClient\Attribute;

const IBM_CONTENTHUB_ATTRIBUTE_FILEURI = '_file_uri';

/**
 * Implements hook_acquia_contenthub_cdf_from_drupal_alter().
 *
 * Allows modules to modify the CDF before it is sent to the Content Hub.
 * Adds an additional attribute to file entities pointing to the local File URI
 * so that the same URI can be used in the subscribing site when recreating this
 * file.
 *
 * @param \Acquia\ContentHubClient\Entity $contenthub_entity
 *   The Content Hub CDF.
 */
function ibm_contenthub_filepath_acquia_contenthub_cdf_from_drupal_alter(ContentHubEntity $contenthub_entity) {

  // Adding changes to the 'file' entity types.
  if ($contenthub_entity->getType() == 'file') {
    $uuid = $contenthub_entity->getUuid();

    // Always check that the changes have already been applied, because the
    // normalizer could be called more than once during the export process.
    if ($contenthub_entity->getAttribute(IBM_CONTENTHUB_ATTRIBUTE_FILEURI) === FALSE) {
      $file = \Drupal::service("entity.repository")->loadEntityByUuid('file', $uuid);
      $uri = $file->getFileUri();
      $attribute = new Attribute(Attribute::TYPE_STRING);
      $attribute->setValue($uri);

      // Setting up new attribute.
      $contenthub_entity->setAttribute(IBM_CONTENTHUB_ATTRIBUTE_FILEURI, $attribute);
    }
  }
}

/**
 * Implements hook_acquia_contenthub_cdf_from_hub_alter().
 *
 * Allows modules to modify the CDF before converting to Drupal Entity.
 * In this case we are using a particular attribute in file entities to create
 * directories in the filesystem that will be used to save those files.
 *
 * @param \Acquia\ContentHubClient\Entity $contenthub_entity
 *   The Content Hub CDF.
 */
function ibm_contenthub_filepath_acquia_contenthub_cdf_from_hub_alter(ContentHubEntity $contenthub_entity) {
  if ($contenthub_entity->getType() == 'file' && !empty($contenthub_entity->getAttribute(IBM_CONTENTHUB_ATTRIBUTE_FILEURI))) {
    $attribute = $contenthub_entity->getAttribute(IBM_CONTENTHUB_ATTRIBUTE_FILEURI);
    $uri = isset($attribute['value']['und']) ? $attribute['value']['und'] : NULL;
    if (substr($uri, 0, 9) === 'public://') {
      // Create directory.
      $path = pathinfo($uri);
      $dir = $path['dirname'];
      list($scheme, $dirs) = explode('://', $dir);
      $directories = explode('/', $dirs);
      $filepath = $scheme . ':/';
      foreach ($directories as $directory) {
        $filepath = $filepath . '/' . $directory;
        if (!is_dir($filepath) || !is_writable($filepath)) {
          if (!file_prepare_directory($filepath, FILE_CREATE_DIRECTORY)) {
            // Log that directory could not be created.
            \Drupal::logger('ibm_contenthub_filepath')
              ->error('Cannot create files subdirectory "!dir". Please check filesystem permissions.', [
                '!dir' => $filepath,
              ]);
          }
        }
      }
    }

  }
}
